// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaamkwzexqpzppgpkozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhYW1rd3pleHFwenBwZ3Brb3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjQyMjgsImV4cCI6MjA2OTkwMDIyOH0.QYdyuSFv5DxChw8NHEG1e21WqCMOUoiFPRcg5uVZoC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});